[build]
  command = "make build"
  functions = "functions"
  publish = "public"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/blugelabs/blugelabs.com"
  GO111MODULE = "on"
